//! `ksp new <name>` — Create a new KSP project from template.

use crate::config::KspConfig;
use crate::ui;
use colored::Colorize;
use std::path::Path;

pub fn run(name: &str, json: bool) {
    if !json {
        ui::print_header(&format!("Creating KSP Project: {}", name));
    }

    let project_dir = Path::new(name);

    if project_dir.exists() {
        if json {
            ui::json_output(
                &serde_json::json!({"status": "error", "message": "Directory already exists"}),
            );
        } else {
            ui::failure(&format!("Directory '{}' already exists.", name));
        }
        return;
    }

    let steps: Vec<(&str, Result<(), String>)> = vec![
        ("Creating project directory", create_dir(project_dir)),
        ("Creating ksp.toml", create_config(project_dir, name)),
        ("Creating certs/", create_certs(project_dir)),
        (
            "Generating self-signed certificate",
            generate_cert(project_dir),
        ),
        ("Creating src/main.rs", create_src(project_dir, name)),
        ("Creating examples/", create_examples(project_dir)),
        ("Creating README.md", create_readme(project_dir, name)),
    ];

    let mut all_ok = true;
    for (step, result) in &steps {
        match result {
            Ok(()) => {
                if !json {
                    ui::success(step);
                }
            }
            Err(e) => {
                if !json {
                    ui::failure(&format!("{}: {}", step, e));
                }
                all_ok = false;
            }
        }
    }

    if json {
        ui::json_output(&serde_json::json!({
            "status": if all_ok { "ok" } else { "error" },
            "project": name,
        }));
    } else if all_ok {
        ui::summary_ok(&format!("Project '{}' created successfully!", name));
        println!("  Project structure:");
        println!("    {}/", name.bold());
        println!("    ├── {}", "ksp.toml".dimmed());
        println!("    ├── {}/", "certs".dimmed());
        println!("    │   ├── {}", "server.cert".dimmed());
        println!("    │   └── {}", "server.key".dimmed());
        println!("    ├── {}/", "src".dimmed());
        println!("    │   └── {}", "main.rs".dimmed());
        println!("    ├── {}/", "examples".dimmed());
        println!("    │   └── {}", "echo_server.rs".dimmed());
        println!("    └── {}", "README.md".dimmed());
        println!();
        println!("  Get started:");
        println!("    {}  cd {}", "→".cyan(), name.bold());
        println!("    {}  ksp server start", "→".cyan());
        println!();
    }
}

fn create_dir(dir: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dir).map_err(|e| e.to_string())
}

fn create_config(dir: &Path, name: &str) -> Result<(), String> {
    let mut config = KspConfig::default();
    config.project.name = name.to_string();
    std::fs::write(dir.join("ksp.toml"), config.to_toml()).map_err(|e| e.to_string())
}

fn create_certs(dir: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dir.join("certs")).map_err(|e| e.to_string())
}

fn generate_cert(dir: &Path) -> Result<(), String> {
    let (cert, key) =
        ksp_crypto::certificate::KspCertificate::generate_self_signed("ksp://localhost", 365);
    std::fs::write(dir.join("certs/server.cert"), cert.serialize()).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("certs/server.key"), key.to_bytes()).map_err(|e| e.to_string())?;
    Ok(())
}

fn create_src(dir: &Path, name: &str) -> Result<(), String> {
    std::fs::create_dir_all(dir.join("src")).map_err(|e| e.to_string())?;
    let content = format!(
        r#"//! {} — KSP Application
//!
//! Generated by `ksp new`.

fn main() {{
    println!("Hello from {}!");
    println!("Start the KSP server with: ksp server start");
    println!("Connect with: ksp connect 127.0.0.1:9876");
}}
"#,
        name, name
    );
    std::fs::write(dir.join("src/main.rs"), content).map_err(|e| e.to_string())
}

fn create_examples(dir: &Path) -> Result<(), String> {
    std::fs::create_dir_all(dir.join("examples")).map_err(|e| e.to_string())?;
    let content = r#"//! Echo Server Example
//!
//! A minimal KSP echo server that reflects encrypted packets back to clients.
//!
//! Usage:
//!   ksp server start
//!   ksp connect 127.0.0.1:9876

fn main() {
    println!("Run `ksp server start` to launch the echo server.");
    println!("Then `ksp connect 127.0.0.1:9876` from another terminal.");
}
"#;
    std::fs::write(dir.join("examples/echo_server.rs"), content).map_err(|e| e.to_string())
}

fn create_readme(dir: &Path, name: &str) -> Result<(), String> {
    let content = format!(
        r#"# {}

A project built with the [Kush Secure Protocol (KSP)](https://www.kspprotocol.dev).

## Quick Start

```bash
# Start the server
ksp server start

# Connect from another terminal
ksp connect 127.0.0.1:9876

# Ping the server
ksp ping 127.0.0.1:9876

# Run diagnostics
ksp doctor
```

## Configuration

Edit `ksp.toml` to customize server settings, security parameters, and logging.

## Learn More

- [KSP Documentation](https://www.kspprotocol.dev)
- [RFC Specification](https://www.kspprotocol.dev/rfc)
- [GitHub Repository](https://github.com/Kush2272/ksp)
"#,
        name
    );
    std::fs::write(dir.join("README.md"), content).map_err(|e| e.to_string())
}
