//! `ksp wireshark install|open|uninstall` — Wireshark Lua Dissector plugin management.

use crate::ui;
use colored::Colorize;
use std::fs;
use std::path::PathBuf;

fn get_wireshark_plugin_path() -> PathBuf {
    #[cfg(target_os = "windows")]
    let mut dir = PathBuf::from(std::env::var("APPDATA").unwrap_or_else(|_| "C:\\Users\\kush\\AppData\\Roaming".into()));
    #[cfg(not(target_os = "windows"))]
    let mut dir = match std::env::var("HOME") {
        Ok(h) => PathBuf::from(h).join(".config"),
        Err(_) => PathBuf::from("/tmp"),
    };

    dir.push("Wireshark");
    dir.push("plugins");
    fs::create_dir_all(&dir).ok();
    dir.push("ksp.lua");
    dir
}

pub fn run_install(json: bool) {
    let path = get_wireshark_plugin_path();
    let lua_code = r#"-- Kush Secure Protocol (`ksp.lua`) Wireshark Dissector
-- Automatically generated by `ksp wireshark install`

ksp_proto = Proto("ksp", "Kush Secure Protocol (KSP)")

-- Header fields
local f_ver = ProtoField.uint8("ksp.version", "Version", base.DEC)
local f_type = ProtoField.uint8("ksp.type", "Packet Type", base.HEX)
local f_flags = ProtoField.uint16("ksp.flags", "Flags", base.HEX)
local f_session = ProtoField.bytes("ksp.session", "Session ID")
local f_stream = ProtoField.uint32("ksp.stream", "Stream ID", base.DEC)
local f_seq = ProtoField.uint64("ksp.sequence", "Sequence #", base.DEC)
local f_nonce = ProtoField.bytes("ksp.nonce", "AEAD Nonce")
local f_payload = ProtoField.bytes("ksp.payload", "Encrypted Payload")
local f_tag = ProtoField.bytes("ksp.tag", "AEAD Auth Tag")

ksp_proto.fields = { f_ver, f_type, f_flags, f_session, f_stream, f_seq, f_nonce, f_payload, f_tag }

function ksp_proto.dissect(buffer, pinfo, tree)
    if buffer:len() < 48 then return end
    pinfo.cols.protocol = "KSP"
    
    local subtree = tree:add(ksp_proto, buffer(), "KSP Protocol Data Unit")
    subtree:add(f_ver, buffer(0, 1))
    subtree:add(f_type, buffer(1, 1))
    subtree:add(f_flags, buffer(2, 2))
    subtree:add(f_session, buffer(4, 16))
    subtree:add(f_stream, buffer(20, 4))
    subtree:add(f_seq, buffer(24, 8))
    subtree:add(f_nonce, buffer(32, 16))
    
    if buffer:len() > 64 then
        subtree:add(f_payload, buffer(48, buffer:len() - 64))
        subtree:add(f_tag, buffer(buffer:len() - 16, 16))
    elseif buffer:len() > 48 then
        subtree:add(f_payload, buffer(48, buffer:len() - 48))
    end
end

local udp_port = DissectorTable.get("udp.port")
udp_port:add(9876, ksp_proto)
local tcp_port = DissectorTable.get("tcp.port")
tcp_port:add(9876, ksp_proto)
"#;

    match fs::write(&path, lua_code) {
        Ok(_) => {
            if json {
                println!("{}", serde_json::json!({"status": "installed", "plugin_path": path.display().to_string()}));
            } else {
                ui::header("Wireshark Dissector Plugin Installation");
                println!("  {} Successfully installed KSP Lua Dissector -> {}", "✔".green().bold(), path.display().to_string().white().bold());
                println!("  {} Registered TCP and UDP port 9876 to `ksp_proto`.", "✔".green().bold());
                println!("  {} Open Wireshark and use display filter `{}`.", "ℹ".blue(), "ksp".yellow().bold());
                println!();
            }
        }
        Err(e) => {
            if json {
                println!("{}", serde_json::json!({"status": "error", "message": e.to_string()}));
            } else {
                ui::failure(&format!("Failed to write Wireshark plugin: {}", e));
            }
        }
    }
}

pub fn run_open(json: bool) {
    if json {
        println!("{}", serde_json::json!({"status": "info", "message": "Launch wireshark with -Y ksp"}));
        return;
    }
    ui::header("Launching Wireshark");
    println!("  {} To filter KSP traffic directly in Wireshark, use: {}", "ℹ".blue(), "wireshark -k -Y ksp -i loopback".yellow().bold());
    println!();
}

pub fn run_uninstall(json: bool) {
    let path = get_wireshark_plugin_path();
    let existed = path.exists();
    let _ = fs::remove_file(&path);

    if json {
        println!("{}", serde_json::json!({"status": "uninstalled", "was_installed": existed}));
        return;
    }

    if existed {
        ui::success("Removed KSP Lua Dissector plugin from Wireshark.");
    } else {
        ui::info("Wireshark plugin was not currently installed.");
    }
    println!();
}
