# FUNDING.yml
# Details: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [Kush2272]
patreon: kush2272
custom: ["https://kushsecureprotocol.org/donate"]
