//! KSP project configuration management (`ksp.toml`).
//!
//! Handles configuration loading, TOML serialization/deserialization,
//! and resolution of active profiles and environments.

use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// KSP project configuration, serialized as `ksp.toml`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KspConfig {
    /// General project settings.
    pub project: ProjectConfig,
    /// Server settings.
    pub server: ServerConfig,
    /// Security settings.
    pub security: SecurityConfig,
    /// Logging settings.
    pub logging: LoggingConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectConfig {
    /// Project name.
    pub name: String,
    /// Protocol version.
    pub version: String,
    /// Description.
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerConfig {
    /// Bind host.
    pub host: String,
    /// Bind port.
    pub port: u16,
    /// Maximum concurrent connections.
    pub max_connections: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityConfig {
    /// Preferred cipher suite: "aes-256-gcm" or "chacha20-poly1305".
    pub cipher: String,
    /// Enable compression.
    pub compression: bool,
    /// Replay window size.
    pub replay_window: u64,
    /// Path to certificate file.
    pub cert_file: String,
    /// Path to private key file.
    pub key_file: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoggingConfig {
    /// Log level: "trace", "debug", "info", "warn", "error".
    pub level: String,
    /// Log format: "pretty" or "json".
    pub format: String,
}

impl Default for KspConfig {
    fn default() -> Self {
        Self {
            project: ProjectConfig {
                name: "my-ksp-project".into(),
                version: "1.0".into(),
                description: "A KSP protocol application".into(),
            },
            server: ServerConfig {
                host: "0.0.0.0".into(),
                port: 9876,
                max_connections: 256,
            },
            security: SecurityConfig {
                cipher: "aes-256-gcm".into(),
                compression: true,
                replay_window: 1024,
                cert_file: "certs/server.cert".into(),
                key_file: "certs/server.key".into(),
            },
            logging: LoggingConfig {
                level: "info".into(),
                format: "pretty".into(),
            },
        }
    }
}

/// Return the persistent user configuration directory for KSP (`~/.ksp` or `%APPDATA%\ksp`).
pub fn user_config_dir() -> PathBuf {
    if let Ok(home) = std::env::var("KSP_HOME") {
        return PathBuf::from(home);
    }
    if let Ok(appdata) = std::env::var("APPDATA") {
        let mut p = PathBuf::from(appdata);
        p.push("ksp");
        let _ = std::fs::create_dir_all(&p);
        return p;
    }
    if let Ok(home) = std::env::var("HOME").or_else(|_| std::env::var("USERPROFILE")) {
        let mut p = PathBuf::from(home);
        p.push(".ksp");
        let _ = std::fs::create_dir_all(&p);
        return p;
    }
    let mut p = std::env::temp_dir();
    p.push("ksp");
    let _ = std::fs::create_dir_all(&p);
    p
}

impl KspConfig {
    /// Generate TOML string from config using accurate TOML serialization.
    pub fn to_toml(&self) -> String {
        let mut out = String::new();
        out.push_str("# ═══════════════════════════════════════════════════\n");
        out.push_str("# KSP Project Configuration\n");
        out.push_str("# Generated by `ksp init` / `ksp config`\n");
        out.push_str("# Docs: https://www.kspprotocol.dev/docs/config\n");
        out.push_str("# ═══════════════════════════════════════════════════\n\n");

        if let Ok(serialized) = toml::to_string(self) {
            out.push_str(&serialized);
        }
        out
    }

    /// Load config from a `ksp.toml` file path using robust TOML parsing.
    pub fn load(path: &Path) -> Result<Self, String> {
        let contents = std::fs::read_to_string(path)
            .map_err(|e| format!("Failed to read {}: {}", path.display(), e))?;
        toml::from_str(&contents)
            .map_err(|e| format!("TOML parse error in {}: {}", path.display(), e))
    }

    /// Find `ksp.toml` by searching upwards from the current directory, or check active profile.
    pub fn find_config() -> Option<PathBuf> {
        if let Ok(mut dir) = std::env::current_dir() {
            loop {
                let candidate = dir.join("ksp.toml");
                if candidate.exists() {
                    return Some(candidate);
                }
                if !dir.pop() {
                    break;
                }
            }
        }

        // Check active profile in user config dir if local ksp.toml not found
        let profile_dir = user_config_dir().join("profiles");
        let active_profile = crate::cmd::profile::get_active_profile();
        let candidate = profile_dir.join(format!("{}.toml", active_profile));
        if candidate.exists() {
            return Some(candidate);
        }

        None
    }
}
